version: '3.8'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/app
    command: npm run start:dev

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: